name = "Eggcraft"
author = "Spellbook Studios"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3119d7509549fc9beb11eb6b4c1b37d64bbdc9477f522ef75c473eec930897f4"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
