name = "Eggcraft"
author = "Spellbook Studios"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8031f88335dece5e43faf78f7570c7b9bd8fb1d81e2712fcac0a08e0ffabed7a"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
