name = "Eggcraft"
author = "Spellbook Studios"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e11b2748505075b1ae867cc23e0857ab8966ace24d2049dbb283edb3726feb8"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
