word = "gzog6zilzq6zxlt"
hasChosenLineReport = true
tripleQuestionMarkInessentiel = 1000
npcFinderThingMaxDistanceChangeBeforeCacheInvalid = 0.5
playAllSoundsOnPlayer = false
reportMissingLines = true
anonymous = false
sendFunFact = true
blockCutOff = 32
highlightSpeaker = false
logDialogueLines = false
onlyLogNotPlayingLines = true
logPlayingInformation = false
