name = "Machines & Magecraft"
author = "Spellbook Studios"
version = "1.0.0a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ffcf64b53e0e2ea22561189d561e69aabbbc671c2760213716f8dd6c233ee79"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.79"
