name = "Machines & Magecraft"
author = "Spellbook Studios"
version = "1.0.0a-beta6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fa2756b9b05486f8f51b9255ca5eae1b8e9029bda67997dd6a3de4954abf2f6"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.79"
