name = "Machines & Magecraft"
author = "Spellbook Studios"
version = "1.0.0a-beta3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f733c00d61bf9b387993c808b18a2b33e3795467a1c094e203631ae1c83651d"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.79"
