name = "Machines & Magecraft"
author = "Spellbook Studios"
version = "1.0.0a-beta5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0234a1a5b15964f551ecab70a30aac999965f8aaee233dde78cbd4b347c938f1"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.79"
