name = "Machines & Magecraft"
author = "Spellbook Studios"
version = "1.0.0a-beta9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40cc8ea52bd82a166975a5ad9071d80714a8c143ce87a3f94fc3cf0615e07a8c"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.79"
