name = "Machines & Magecraft"
author = "Spellbook Studios"
version = "1.0.0a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5541d0f15797030534ebab7881a85bdeeb9c43c340aaafa4b9c830577576bb76"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.79"
