name = "Machines & Magecraft"
author = "Spellbook Studios"
version = "1.0.0a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2886727672d2c66fa801822c5f243cf95913c1e23ec1f904ce592ad24868bfe7"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.79"
