name = "Machines & Magecraft"
author = "Spellbook Studios"
version = "1.0.0a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58a6a5854df942a4b298e7f461f5ebd7cab917d5f714d6571079a0be3692bffc"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.79"
