name = "Machines & Magecraft"
author = "Spellbook Studios"
version = "1.0.0a-beta2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21179760e2b47e85e499fc093678e268ea42ef37dd74fa4ce29062de5440c7b7"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.79"
