name = "Machines & Magecraft"
author = "Spellbook Studios"
version = "1.0.0a-beta9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d32c2ed9cb9f42718f9244c62be6f8dd8a21b309725e37b6a1f130a81d824e53"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.79"
