name = "Machines & Magecraft"
author = "Spellbook Studios"
version = "1.0.0a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "271b98e8aa1ec04a1d02e4f8f3ce4aef5778e44743603faa00797ebca91f637d"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.79"
