name = "Machines & Magecraft"
author = "Spellbook Studios"
version = "1.0.0a-beta8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54bdd357d7c787380acd15f5d17a55c4dfb697465c376b6a63a3610c717be867"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.79"
