name = "Wynncraft Ultimate"
author = "Spellbook Studios"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e899691dc4466a89cbcd006e4921e3fada9433430a3b9b0390b27e0da74e0bd0"

[versions]
fabric = "0.14.22"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19.3"]
