name = "Wynncraft Ultimate"
author = "Spellbook Studios"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4dcc8a65ba60a987b2708662b69efbc90f31f485abb47728f590e70c112b999d"

[versions]
minecraft = "1.19.4"
quilt = "0.19.1-beta.3"
