name = "Wynncraft Ultimate"
author = "Spellbook Studios"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c928e444001233fc4551724d1c958d252e52700095ceb8b647901d211b6fe7bd"

[versions]
minecraft = "1.20.1"
quilt = "0.19.3-beta.1"

[options]
acceptable-game-versions = ["1.20"]
