name = "Wynncraft Ultimate"
author = "Spellbook Studios"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e8d766e0ce1e345316b8bbdec33bb4b7351eb138f3a566137d3c472c21c09c3"

[versions]
minecraft = "1.19.4"
quilt = "0.19.1-beta.3"
