name = "Wynncraft Ultimate"
author = "Spellbook Studios"
version = "1.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0efdbe13c15a036d3270f93f8354d3e7def251b11ad085825173dd85b4538c80"

[versions]
fabric = "0.15.6"
minecraft = "1.20.2"

[options]
acceptable-game-versions = []
