name = "Wynncraft Ultimate"
author = "Spellbook Studios"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7468a741d8704df82b9578786747a6f2ab06bf97f8b09d3dd62cddcb643e2b45"

[versions]
fabric = "0.14.22"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19.3"]
